<?php 
////////////////////////////////////////////////////////////////////////
//  EasyOChem marvintinymcestudent filter for use with eomarvin2d TinyMCE plugin
// 
//  This filter will replaces <mar></mar>
// with the Javascript needed to display the molecular structure inline
//
//  To activate this filter, go to admin and enable 'marvintinymcestudent' 
// which will also display the button in TinyMCE editor.
//
//
//  Filter written by Carl LeBlond
//
////////////////////////////////////////////////////////////////////////



class filter_marvintinymcestudent extends moodle_text_filter {


function filter($text, array $options = array()){
    global $CFG, $tinymce_applet_has_been_initialised;
    
   

$callbackfunction='';


if(preg_match_all("'\[.*?{.*?{(.*?)}}\]|<mar>(.*?)</mar>'si", $text, $matches)){
/*
if(preg_match_all("'<span.*?mar2d mceNonEditable.*?>(.*?)</span>'si", $text, $matches)){

/*
if(preg_match_all("'<span.*?mar2d mceNonEditable.*?>(.*?)</span>|<mar>(.*?)</mar>'si", $text, $matches)){
*/
//preg_match_all("'<span class=\"mar2d mceNonEditable\">(.*?)</span>'si", $text, $match);
//if($match) echo "result=".$match[1];


//var_dump($matches);
//echo "0".$matches[0][0]."<br>";
//echo "1".$matches[0][1]."<br>";
//echo "2".$matches[0][2]."<br>";

$count = 0;


//var_dump($matches);

$callbackfunction = '


global $count;
$a=$count++;

if($a=="")$a=0;

$mrvfile=$matches[0];
//echo "<br>a,mrv= $a <br> $mrvfile";
$mrvfile=str_replace( "[{{", "", $mrvfile);
if(preg_match_all( "/\[(.*?){(.*?){/", $mrvfile, $dimensions))
{
//var_dump($dimensions);

//echo "<br>".$dimensions[0];
//echo "<br>".
$width=$dimensions[1][0];
$height=$dimensions[2][0];
}
else{
$width=600;
$height=300;
}

$mrvfile=preg_replace( "/\[(.*?){(.*?){/", "", $mrvfile);

$mrvfile=str_replace( "}}]", "", $mrvfile);
$mrvfile=str_replace( "<mar>", "", $mrvfile);
$mrvfile=str_replace( "</mar>", "", $mrvfile);
//$mrvfile=str_replace( "&lt;", "<", $mrvfile);
//$mrvfile=str_replace( "&gt;", ">", $mrvfile);
//$mrvfile=addslashes($mrvfile);
//$mrvfile=htmlentities($mrvfile);
/*
$mrvfile="<?xml version=\"1.0\" encoding=\"UTF-8\"?><cml xmlns=\"http://www.chemaxon.com\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.chemaxon.com/marvin/help/formats/schema/mrvSchema_6_1_0.xsd\" version=\"ChemAxon file format v6.1, generated by v6.1.3\"><MDocument></MDocument></cml>";
*/








$replace="
<applet id=\"MSketch$a\" height=\"$height\" width=\"$width\" code=\"chemaxon.marvin.applet.JMViewLaunch\" archive=\"appletlaunch.jar\" name=\"MSketch$a\" codebase=\"/marvin\" ><param name=\"tabScale\" value=\"28\"><param name=\"navmode\" value=\"translate\"><param name=\"codebase_lookup\" value=\"false\"><param name=\"mol\" value=\'$mrvfile\'><param name=\"chargeWithCircle\" value=\"@javascript-URI-encoded@true\">
<param name\"codebase_lookup\" value=\"@javascript-URI-encoded@false\">
<param name=\"implicitH\" value=\"@javascript-URI-encoded@hetero\">
<param name=\"legacy_lifecycle\" value=\"false\">
<param name=\"java_arguments\" value=\"-Djnlp.packEnabled=true -Xmx512m\">
<center><b>YOU CANNOT SEE A JAVA APPLET HERE</b></center>
<param name=\"codebase_lookup\" value=\"false\"></applet> 
";

return $replace;


';



}





        $search = "'\[.*?{.*?{(.*?)}}\]|<mar>(.*?)</mar>'si";

//        $search = "'<span(.*?)class=\"mar2d mceNonEditable\">(.*?)</span>|/<mar>(.*?)<\/mar>'si";




$newtext = preg_replace_callback($search, create_function('$matches', $callbackfunction), $text);
//echo "<br>";

 
if(($newtext != $text) && !isset($tinymce_applet_has_been_initialised)){
      $$tinymce_applet_has_been_initialised = true;
           
  } 
return $newtext;
}
}
?>
